name: WordPress VIP Go Standards

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3'
        extensions: mbstring
        ini-values: opcache.jit_buffer_size=256M, opcache.jit=1235, pcre.jit=1
        coverage: pcov
        tools: php-cs-fixer, phpunit

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      
    - name: Run phpcs
      run: ./vendor/bin/phpcs --extensions=php --standard=WordPress-VIP-Go,WordPress-Docs ./ --ignore=.idea/*,vendor/*
